---

- name: Are we inside docker?
  ansible.builtin.include_role:
    name: amolofos.ansible_collection_workstation.utils.are_we_in_docker

- name: Upgrade to latest software packages
  ansible.builtin.include_role:
    name: amolofos.ansible_collection_workstation.software
  vars:
    state: upgrade
    cache_valid_time: "{{ package_manager.cache_valid_time }}"
  when:
    - software is defined

- name: Cleanup
  ansible.builtin.include_role:
    name: amolofos.ansible_collection_workstation.software
  vars:
    state: cleanup
