---

- name: Are we inside docker?
  include_role:
    name: utils/are_we_in_docker

- name: Upgrade to latest software packages
  include_role:
    name: software
  vars:
    state: upgrade
    cache_valid_time: "{{ package_manager.cache_valid_time }}"
  when:
    - software is defined

- name: Cleanup
  include_role:
    name: software
  vars:
    state: cleanup
