---

- name: Are we inside docker?
  ansible.builtin.include_role:
    name: amolofos.ansible_collection_workstation.utils.are_we_in_docker

- name: Configure locale
  ansible.builtin.include_role:
    name: amolofos.ansible_collection_workstation.system.locale

- name: Configure timezone
  ansible.builtin.include_role:
    name: amolofos.ansible_collection_workstation.system.timezone
