---

- name: Are we inside docker?
  include_role:
    name: utils/are_we_in_docker

- name: Configure locale
  include_role:
    name: system/locale

- name: Configure timezone
  include_role:
    name: system/timezone
