---

- name: Update initramfs  # noqa fqcn[action-core]
  register: update_initramfs_out
  become: true
  become_user: "root"
  ansible.builtin.shell: >-
    update-initramfs -u -k $(uname -r)
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Logs for update-initramfs
  ansible.builtin.debug:
    msg: "{{ update_initramfs_out }}"
  changed_when: false
