name: Default

on:

  # Triggers the workflow on push or pull request events that target the main and release branches.
  push:
    branches:
    - main
    - release/*

  # Trigger the workflow to run on pull_request events that target the main and release branches.
  pull_request:
    branches:
      - main
      - release/*

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:

  test:
    name: Test on docker

    runs-on: ubuntu-latest

    env:
      PUBLISH_COLLECTION: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v2

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main

      - name: Build collection
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: '${{ secrets.GALAXY_API_KEY }}'
          build: true
          publish: false
