name: Release

on:

  pull_request:
    branches:
      - main
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:

  release:
    name: Release collection

    runs-on: ubuntu-latest

    env:
      PUBLISH_COLLECTION: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true }}

    if: ${{ env.PUBLISH_COLLECTION }}
    steps:
      - uses: actions/checkout@v2

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main

      - name: Build and publish collection
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: '${{ secrets.GALAXY_API_KEY }}'
          build: true
          publish: true
